### ISSUE TITLE
Add Turtle Rover tweet

### ISSUE THREAD

**Issue by annakrystalli** [annakrystalli/LucyElen-learns-robotics#2]
We got another contribution after tweeting out our site. Needs to be added. Probably makes sense under the **Lego Robotics** section? What do you think @Lucy-ElenK ?

Here's the link to the tweet: https://twitter.com/TurtleRover/status/1081113886554636288

I'm assigning it to you as an exercise 😸
Make a pull request so we can review it together.

Here's info on **how to embed tweets**: https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview.html

**Comment by Lucy-ElenK** [comment]
Thanks, for the exercise I will do my best and make the information better
then the last one. If I have any questions can I ask you because you know
I'm new in this so maybe I would need some help 🤓

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by annakrystalli** [comment]
Sure thing!

Here's a link to info on how to embed YouTube videos. https://support.google.com/youtube/answer/171780?hl=en

Any more questions, just let me know ❤️

**Comment by annakrystalli** [comment]
Nice work Lucy Elen! 🚀

I can see you added this in commit https://github.com/annakrystalli/LucyElen-learns-robotics/commit/1c77c4588a2151eae91bb270ed3f04e52da8d306 so seeing as this issue is resolved, I will close it. 😁

**Comment by Lucy-ElenK** [comment]
Ok! 😅 I'm glad that everything is solved and the I pasted a little test
you gave me. Soon (in a week or something) I will order the crafty robot I
will text when I need your address so it will go to your house and when I
come there on February you will have it. I can't wait to see you again on
February. See you soon.😘😃😄🤗😸

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Lucy-ElenK** [comment]
I tried to put the video on but I can't when I put it on I Commit the
changes and blah blah blah 😅. When I go back to the website is not there.
I go again back to the index and the place I put it on is just blank.❓❓❓❓.
How did that happened. I will send you the link so you put it on because
now I'm really annoyed of this.
https://youtu.be/QS7iAhhMRHY
this is the link of the video please put it on. For a moment I thought that
the website doesn't have any more space but I don't think so.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by annakrystalli** [comment]
Hehe it's because you made a pull request rather than a direct commit to master.  You can see it  here: #4 

Remember the pull request is like a suggestion. It allows us to look at your proposal and then merge it in if we are happy with it. 

Also, I think you want to embed the video rather then just add the link right? So the code to embed the video is this:


<iframe width="560" height="315" src="https://www.youtube.com/embed/QS7iAhhMRHY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

I'll try and edit thhe pull request and merge it in :)

**Comment by annakrystalli** [comment]
OK I reopened the issue because we haven't finished with it yet.

I changed the code in the pull request (#4 ) to embed the video rather than just add the link.

Because you are a collaborator, you can merge the pull request in too. So I will let you do it. Just click on the pull request link (#4 ) and then click on the green **Merge Pull Request** button.

After that, you can close this issue again 😸

**Comment by annakrystalli** [comment]
Hey lovely! Looks like you fixed the video?

**Comment by Lucy-ElenK** [comment]
Yap 😃🤗😄🤗😃🤗😃😄😃😃😄🤗

**Comment by annakrystalli** [comment]
💯Nice work!

I thought of a different challenge for you next. I'll open another issue for it tonight 😉

**Comment by annakrystalli** [comment]
Will close this one now because you've completed it! 🚀
